### ISSUE TITLE
caffe make runtest error.

### ISSUE THREAD

**Issue by 491734045** [NVIDIA/caffe#237]
I want to install caffe on ubuntu 14.04. There is no problem in make and make test process, but make runtest process  occurs error as follow: 
[ RUN      ] SoftmaxWithLossLayerTest/3.TestForwardIgnoreLabel F0914 08:13:06.556107  2981 cudnn_softmax_layer.cu:20] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
my graphic card, driver, CUDA and cuDNN versions are as follow:
Graphic card: GT 740
NVIDIA-SMI: 352.63
CUDA: release 7.5, V7.5.17
cuDNN: cudnn-8.0-linux-x64-v5.1

I wonder if the versions above are compatible? If they are compatible, what causes this error?

**Comment by drnikolaev** [comment]
Is this v0.15.13? Also, does this happen with CUDA 8.0 RC?

**Comment by 491734045** [comment]
@drnikolaev 
Yes, the caffe version is v0.15.13.  The CUDA version is 7.5

**Comment by drnikolaev** [comment]
Could you try CUDA 8.0 RC please?

**Comment by 491734045** [comment]
@drnikolaev The problem has been solved. The cuDNN version "cudnn-8.0-linux-x64-v5.1" is not compatible with the CUDA 7.5. Instead, cudnn-7.5-linux-x64-v5.1 works! 
Thanks for your help!
