### ISSUE TITLE
NVIDIA/Caffe bug: CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#299]
Hi,

I have been trying to load the fcn8-s network outside a loop (once) and use the net in a for loop to infer on images of different sizes (<1200 x 1900). here is the example code: 

for path in paths:
    in_image=cv2.imread(path)
    net.blobs['data'].reshape(1,in_image.shape[2],in_image.shape[0],in_image.shape[1])
    output = net.forward() # crashes on the second iteration

All works fine with the latest version of BVLC/caffe!! yes!
However, the NVIDIA/Caffe throws out this error on the second image:
Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

I have tried the following cases:
both re-trained fcn8-s in Digits and original fcn8-s from https://github.com/shelhamer/fcn.berkeleyvision.org/tree/master/voc-fcn8s along with  
1. BVLC/CAFFE + cuda 8.0 + libcudnn5-dev         => all works great
1. NVIDIA//CAFFE  + cuda 7.5 + libcudnn55-dev => above ERROR
2. NVIDIA//CAFFE +  cuda 8.0 + libcudnn5-dev   => above ERROR

I have tested with both   
convolution_param {
    engine: CAFFE
and 
    engine: CUDNN

no success with nvidia/caffe...
any suggestions ?

hi @gheinrich, you have tried fcn8-s with nvcaffe, maybe you have some insight?

**Comment by gheinrich** [comment]
Hello, did you try the latest nv-caffe 0.15.x?

**Comment by RSly** [comment]
@gheinrich yes I am on branch caffe-0.15, latest commit (Merge pull request #288 from lukeyeager/debuild-python-h5py)

maybe I will go back to the v0.15.14, 13 etc tags to test...

**Comment by RSly** [comment]
Just guessing it looks like a memory leak, maybe nv-caffe doesn't release the GPU memory once it is done with net.forward?

**Comment by gheinrich** [comment]
I would try to see if it works better if you always provide batches of the same shape.

**Comment by RSly** [comment]
@gheinrich I tracked down the problem,

it comes from the commit: 
Hot fixe preventing redundant Find*Ex calls during TEST phase

It all works nicely when, in the latest nv-caffe, I revert the above commit by commenting the line
use_modest_workspace_ = false;
in 
src/caffe/layers/cudnn_conv_layer.cu


What is use_modest_workspace_ = false; suppose to achieve?

**Comment by drnikolaev** [comment]
@RSly Please try cuDNN v6 with caffe-0.16 release.  
use_modest_workspace_ = false;  means that we are done with estimations of memory required for convolution. This code is re-designed in 0.16 release, please check it out.

**Comment by RSly** [comment]
hi @drnikolaev 
I try to build it, cuDNN v6 with nv-caffe-0.16 + cuda 8 + ubuntu 14+ boost ver. 1.61

I get this error at sudo make:
(I will try with different versions of boost or cuda)

/usr/local/include/boost/chrono/duration.hpp(256): error: class "boost::common_type<int_least64_t, int_least64_t, intmax_t>" has no member "type"
/usr/local/include/boost/chrono/duration.hpp(256): error: class "boost::common_type<int_least64_t, int_least64_t, intmax_t>" has no member "type"
          detected during:
            instantiation of "ToDuration boost::chrono::detail::duration_cast_aux<FromDuration, ToDuration, Period, true, false>::operator()(const FromDuration &) const [with FromDuration=boost::chrono::duration<int_least64_t, b
oost::nano>, ToDuration=boost::chrono::seconds, Period=boost::ratio<1L, 1000000000L>]"
(315): here
            instantiation of "ToDuration boost::chrono::detail::duration_cast<FromDuration, ToDuration>::operator()(const FromDuration &) const [with FromDuration=boost::chrono::duration<int_least64_t, boost::nano>, ToDuration=b
oost::chrono::seconds]"
(789): here
            instantiation of "boost::enable_if<boost::chrono::detail::is_duration<ToDuration>, ToDuration>::type boost::chrono::duration_cast<ToDuration,Rep,Period>(const boost::chrono::duration<Rep, Period> &) [with ToDuration=
boost::chrono::seconds, Rep=int_least64_t, Period=boost::nano]"
/usr/local/include/boost/thread/pthread/timespec.hpp(51): here

**Comment by RSly** [comment]
update: with cuda 7.5, it complains about nvml.h [which is part of cuda8 no?]

caffe/include/caffe/util/device_alternate.hpp:45:20:  fatal error: nvml.h: No such file or directory

**Comment by drnikolaev** [comment]
7.5 doesn't come with NVML by default. You may either install it or disable it by using NO_NVML:=1 
For CMake use -DNO_NVML=ON 
Or better use CUDA 8.0

**Comment by RSly** [comment]
@drnikolaev so I summerize my tests:
1. cuda 8.0 + cudnn v6  +nv-caffe-0.16 + boost 1.61
   **cant compile due to the errors regarding boost as reported above**

2. cuda 7.5 + NO_NVML:=1 + cudnn v6  + nv-caffe-0.16+ boost 1.61
   **All works very nice!** and no memory errors. Fantastic
One thing I noticed is that  GPUMemory::Manager doesnt care about
 caffe.set_device(3), it initializes ALL the GPUs, and if they are already in use then this is a problem

is this a bug or is there a way to tell the   GPUMemory::Manager only initialize gpu3 for example?

Thanks a lot for your great work

**Comment by drnikolaev** [comment]
Thanks for the feedback. All GPUs init seems to be an issue, will check it.
As of boost: so, it breaks when you step up from CUDA 7.5 to 8.0, right? That's weird...

**Comment by RSly** [comment]
sounds good
yes cuda 8.0 +boost is not happy

**Comment by RSly** [comment]
The initial issue is solved in 0.16. so I close this issue, and open a new one for the GPU initialization
