### ISSUE TITLE
Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM, device 1

### ISSUE THREAD

**Issue by mxs30443** [NVIDIA/caffe#435]
Hi,
I cann't run nvcaffe with GPU mode.
I am trying to verify the nvcaffe:
`data/mnist/get_mnist.sh`
`examples/mnist/create_mnist.sh`
`examples/mnist/train_lenet.sh`
then I meet this peoblem:

> E1027 14:53:21.139746  3050 common.cpp:496] Cannot create cuDNN handle. cuDNN won't be available.
F1027 14:53:21.139894  3050 common.cpp:498] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM, device 1
*** Check failure stack trace: ***
    @     0x7fa902ca6daa  (unknown)
    @     0x7fa902ca6ce4  (unknown)
    @     0x7fa902ca66e6  (unknown)
    @     0x7fa902ca9687  (unknown)
    @     0x7fa9039c44bf  caffe::CuDNNHandle::CuDNNHandle()
    @     0x7fa9039c74a5  _ZN5boost11make_sharedIN5caffe11CuDNNHandleEP11CUstream_stJEEENS_6detail15sp_if_not_arrayIT_E4typeEOT0_DpOT1_
    @     0x7fa9039c4c6b  caffe::Caffe::device_cudnn_handle()
    @     0x7fa9038fd174  caffe::CuDNNConvolutionLayer<>::AllocateWorkspace()
    @     0x7fa90390c1c8  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7fa903730a40  caffe::Net::Init()
    @     0x7fa903731f86  caffe::Net::Net()
    @     0x7fa9036fde30  caffe::Solver::InitTrainNet()
    @     0x7fa9036fe30f  caffe::Solver::Init()
    @     0x7fa9036fe778  caffe::Solver::Solver()
    @     0x7fa9036e5326  caffe::Creator_SGDSolver()
    @           0x4106c7  caffe::SolverRegistry::CreateSolver()
    @           0x40b4fe  train()
    @           0x409128  main
    @     0x7fa901eb2f45  (unknown)
    @           0x40996b  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

I are working on GTX1080(x2)
--Ubunt14.04
--nvcaffe0.16
--cudnnV6
--cuda8.0

Attached the ldd outputs after running:
ldd libcaffe-nv.so

> 	linux-vdso.so.1 =>  (0x00007ffea7bdd000)
	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007f06a2bd9000)
	libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00007f06a0141000)
	libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00007f069c1cb000)
	libnvidia-ml.so.1 => /usr/lib/nvidia-384/libnvidia-ml.so.1 (0x00007f069bbf8000)
	libboost_system.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0 (0x00007f069b9f4000)
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007f069b7bc000)
	libgflags.so.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2 (0x00007f069b59c000)
	libprotobuf.so.8 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.8 (0x00007f069b29a000)
	libhdf5_hl.so.7 => /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.7 (0x00007f069b06a000)
	libhdf5.so.7 => /usr/lib/x86_64-linux-gnu/libhdf5.so.7 (0x00007f069abce000)
	libleveldb.so.1 => /usr/lib/x86_64-linux-gnu/libleveldb.so.1 (0x00007f069a981000)
	liblmdb.so.0 => /usr/lib/x86_64-linux-gnu/liblmdb.so.0 (0x00007f069a76f000)
	libopencv_core.so.3.0 => /opt/opencv3.0/lib/libopencv_core.so.3.0 (0x00007f069976c000)
	libopencv_imgproc.so.3.0 => /opt/opencv3.0/lib/libopencv_imgproc.so.3.0 (0x00007f06987ea000)
	libopencv_imgcodecs.so.3.0 => /opt/opencv3.0/lib/libopencv_imgcodecs.so.3.0 (0x00007f0698556000)
	libboost_thread.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0 (0x00007f0698340000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f069803c000)
	libcudnn.so.6 => /usr/local/cuda/lib64/libcudnn.so.6 (0x00007f068eada000)
	libnccl.so.1 => /usr/local/lib/libnccl.so.1 (0x00007f068c478000)
	libopenblas.so.0 => /opt/OpenBLAS/lib/libopenblas.so.0 (0x00007f068b4e5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f068b1df000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f068afc9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f068adab000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f068a9e2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f06a41a5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f068a7de000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f068a5d6000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f068a3bb000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f068a1a2000)
	libsnappy.so.1 => /usr/lib/libsnappy.so.1 (0x00007f0689f9c000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f0689d47000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f0689b21000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f06898af000)
	libjasper.so.1 => /usr/lib/x86_64-linux-gnu/libjasper.so.1 (0x00007f0689658000)
	libIlmImf.so.6 => /usr/lib/x86_64-linux-gnu/libIlmImf.so.6 (0x00007f06893a9000)
	libHalf.so.6 => /usr/lib/x86_64-linux-gnu/libHalf.so.6 (0x00007f0689166000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f0688e4c000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f0688c2a000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f0688a1c000)
	libIex.so.6 => /usr/lib/x86_64-linux-gnu/libIex.so.6 (0x00007f06887fe000)
	libIlmThread.so.6 => /usr/lib/x86_64-linux-gnu/libIlmThread.so.6 (0x00007f06885f8000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f06883bc000)

I try to compile the nvcaffe without cudnn,then I found the GPU mode slower than CPU mode.

**Comment by babiking** [comment]
I install 2 GPUs on my PC, i.e. one GTX 650 for graphic display and one GTX 1080Ti for computation.
When I run a classification model, I was confronted with similar problem as above mentioned.

'caffe:Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM'

Then I re-make caffe by comment USE__CUDNN := 1 in Makefile.config. But the computation speed seems being very negatively influenced. Any recommended solution?

**Comment by Jingwei-Liao** [comment]
Hello,I have solved this problem by adding
engine: CAFFE 
in the convolution_param
hope can help you ~

**Comment by drnikolaev** [comment]
Hi @mxs30443 @babiking @woshiljw  --- have you tried to upgrade CuDNN?

**Comment by Jingwei-Liao** [comment]
@drnikolaev
i use cuda7.5 cudnn 5.1
but if you miss the problem
Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM
maybe you should change you discription file of the net
i add 
engine: CAFFE
in the convolution_param of Convolution layer to solve the problem

**Comment by mxs30443** [comment]
@woshiljw @drnikolaev thank you very much

**Comment by thomas-riccardi** [comment]
We got hit by that too, using nv caffe 0.16.4, cuda 8.0, cudnn 7.
This issue should be re-open: the workaround is effectively to disable cudnn, which is not satisafying at all...

**Comment by thomas-riccardi** [comment]
Disabling cudnn for convolutions created high and highly volatile gpu memory usage.

We found a better workaround:
disable the default `cudnn_convolution_algo_seeker: FINDEX` and replace it by the simpler implementation: heuristic engine: `cudnn_convolution_algo_seeker: GET`.
See http://docs.nvidia.com/deeplearning/dgx/caffe-user-guide/index.html#cudnn_convolution_algo_seeker
