### ISSUE TITLE
Getting error while runtest [result == ncclSuccess (1 vs. 0)]  

### ISSUE THREAD

**Issue by Jeffery4000** [NVIDIA/caffe#450]
Hi, while I am trying to install nvidia/caffe with Cmaka got no issue at all which show all the correct parameter. If you need to look at the caffe configuration summary do let me know. 

CUDA Version: CUDA 8.0
NCCL Version: NCCL 2.1
GPU: 4x GTX Titan X 12GB (Maxwell)
OS: Ubuntu 16.04

This is the error message I am getting while running thorough [make runtest]:

•	[----------] 8 tests from RMSPropSolverTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN      ] RMSPropSolverTest/2.TestRMSPropLeastSquaresUpdateWithRmsDecay
**F1206 07:37:19.964359 10589 parallel.cpp:156] Check failed: result == ncclSuccess (1 vs. 0)  unhandled cuda error**
*** Check failure stack trace: ***
F1206 07:37:19.964366 10588 parallel.cpp:156] Check failed: result == ncclSuccess (1 vs. 0)  unhandled cuda error
*** Check failure stack trace: ***
@     0x7f55d9a0f5cd  google::LogMessage::Fail()
@     0x7f55d9a0f5cd  google::LogMessage::Fail()
@     0x7f55d9a11433  google::LogMessage::SendToLog()
@     0x7f55d9a11433  google::LogMessage::SendToLog()
@     0x7f55d9a0f15b  google::LogMessage::Flush()
@     0x7f55d9a0f15b  google::LogMessage::Flush()
@     0x7f55d9a11e1e  google::LogMessageFatal::~LogMessageFatal()
@     0x7f55d9a11e1e  google::LogMessageFatal::~LogMessageFatal()
@     0x7f55dabb1da3  caffe::P2PSync::InternalThreadEntry()
@     0x7f55dabb1da3  caffe::P2PSync::InternalThreadEntry()
@     0x7f55dab70d3b  caffe::InternalThread::entry()
@     0x7f55dab70d3b  caffe::InternalThread::entry()
@     0x7f55dab72ceb  boost::detail::thread_data<>::run()
@     0x7f55dab72ceb  boost::detail::thread_data<>::run()
@     0x7f55da0795d5  (unknown)
@     0x7f55da0795d5  (unknown)
@     0x7f55d9c3a6ba  start_thread
@     0x7f55d9c3a6ba  start_thread
@     0x7f55d3a0b3dd  clone
@     0x7f55d3a0b3dd  clone
@              (nil)  (unknown)
Aborted (core dumped)
src/caffe/test/CMakeFiles/runtest.dir/build.make:57: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 134
CMakeFiles/Makefile2:328: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CMakeFiles/Makefile2:335: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
Makefile:240: recipe for target 'runtest' failed
make: *** [runtest] Error 2

**Comment by cliffwoolley** [comment]
Can you please try running with the following environment variable set and post the relevant bits from the tail end of the NCCL debug output?
```
export NCCL_DEBUG=INFO
```
Thanks,
Cliff

**Comment by drnikolaev** [comment]
hi @Jeffery4000 please try with `export NCCL_DEBUG=WARN` and paste the output here.

**Comment by cliffwoolley** [comment]
Heh, jinx, @drnikolaev .  :)  `=INFO` is just a bit more verbose than `=WARN` but you can go either route, @Jeffery4000 .

**Comment by Jeffery4000** [comment]
Hi @drnikolaev @cliffwoolley , 

Im getting the error message shown below, it might be i had install the wrong NCCL library (cuda8.0 instead of 9.0). Its there a way i can delete the nccl library and install nccl 2.1 (compatible with cuda 8.0)?


[ RUN      ] AdamSolverTest/3.TestAdamLeastSquaresUpdate
lrkow-caffe:10705:10705 [0] INFO NET : Using interface eth0:172.17.0.5<0>
lrkow-caffe:10705:10705 [0] INFO NET/IB : Using interface eth0 for sideband communication
lrkow-caffe:10705:10705 [32767] INFO Using internal Network Socket
lrkow-caffe:10705:10705 [32627] INFO Using NCCL Low-latency algorithm for sizes below 16384
lrkow-caffe:10705:10705 [-1] INFO NET : Using interface eth0:172.17.0.5<0>
lrkow-caffe:10705:10705 [0] INFO NET/Socket : 1 interfaces found

lrkow-caffe:10705:11151 [0] init.cu:537 **WARN NCCL version 2.1.2+cuda9.0**
Cuda failure 'CUDA driver version is insufficient for CUDA runtime version'

lrkow-caffe:10705:11150 [0] init.cu:537 WARN Cuda failure 'CUDA driver version is insufficient for CUDA runtime version'
F1206 16:46:31.762498 11151 parallel.cpp:156] Check failed: result == ncclSuccess (1 vs. 0)  unhandled cuda error
*** Check failure stack trace: ***

**Comment by Jeffery4000** [comment]
I solved this by replacing the correct NCCL library. 

Thanks for all your help. @drnikolaev @cliffwoolley  

sudo apt-get install libnccl2=2.1.2-1+cuda8.0 libnccl-dev=2.1.2-1+cuda8.0

**Comment by cliffwoolley** [comment]
Glad to help!
