### ISSUE TITLE
Check failed: result == ncclSuccess (1 vs. 0)  unhandled cuda error

### ISSUE THREAD

**Issue by TimoSaemann** [NVIDIA/caffe#492]
Hi @drnikolaev 

When running a training with several GPUs: 
_./build/tools/caffe_ train _--solver=models/bvlc_reference_caffenet/solver.prototxt --gpu=0,1_

I get the following error:
_Check_ failed: result == ncclSuccess (1 vs. 0)  unhandled cuda _error_

Please find the complete output log and the cmake output log attached.
[nvcaffe_train_2GPUS.log](https://github.com/NVIDIA/caffe/files/1874806/nvcaffe_train_2GPUS.log)
[nvcaffe_cmake.log](https://github.com/NVIDIA/caffe/files/1874819/nvcaffe_cmake.log)

**Comment by drnikolaev** [comment]
Hi @TimoSaemann 
```
I0404 10:13:38.892127 12760 caffe.cpp:454] This is NVCaffe 0.16.6 started at Wed Apr  4 10:13:38 2018
I0404 10:13:38.892240 12760 caffe.cpp:456] CuDNN version: 6021
I0404 10:13:38.892243 12760 caffe.cpp:457] CuBLAS version: 8000
I0404 10:13:38.892246 12760 caffe.cpp:458] CUDA version: 8000
I0404 10:13:38.892247 12760 caffe.cpp:459] CUDA driver version: 9000
```
If possible, please upgrade to the latest 0.17 code and link with CuDNN 7, CUDA 9 and NCCL 2

**Comment by TimoSaemann** [comment]
I installed NCCL via sudo apt install libnccl2 libnccl-dev and installed the version suitable for CUDA 9. 
I had to specify CUDA 8 during installation as follows: sudo apt-get install libnccl2=2.1.15-1+cuda8.0 libnccl-dev=2.1.15-1+cuda8.0
Now it works.
