### ISSUE TITLE
Error training with multi-GPU in 0.13

### ISSUE THREAD

**Issue by alfredox10** [NVIDIA/caffe#76]
I get absolutely no errors training on a single GPU on this branch, and never have in the past. This is the first time I try training multi-GPU and I am getting this error at random iterations. Sometimes it's around 8K, sometimes it's around iter 20K. Is this a known issue?

This is the command I use to train:
build/tools/caffe train --solver=examples/bibsmart/bibsmart_solver.prototxt -gpus all

```
I1116 15:54:52.782349 30214 solver.cpp:314] Iteration 28053, Testing net (#0)
I1116 15:54:58.068253 30214 solver.cpp:363]     Test net output #0: accuracy1 = 0.951467
I1116 15:54:58.068287 30214 solver.cpp:363]     Test net output #1: loss1 = 0.139663 (* 1 = 0.139663 loss)
F1116 15:55:02.388101 30214 cudnn_conv_layer.cu:137] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered
*** Check failure stack trace: ***
    @     0x7f2b138a6daa  (unknown)
    @     0x7f2b138a6ce4  (unknown)
    @     0x7f2b138a66e6  (unknown)
    @     0x7f2b138a9687  (unknown)
    @     0x7f2b13f9526f  caffe::CuDNNConvolutionLayer<>::Backward_gpu()
    @     0x7f2b13f66d37  caffe::Net<>::BackwardFromTo()
    @     0x7f2b13f66ea1  caffe::Net<>::Backward()
    @     0x7f2b13e86506  caffe::Solver<>::Step()
    @     0x7f2b13e86ffe  caffe::Solver<>::Solve()
    @     0x7f2b13e8fb58  caffe::P2PSync<>::run()
    @           0x407374  train()
    @           0x405311  main
    @     0x7f2b12db7ec5  (unknown)
    @           0x40593b  (unknown)
    @              (nil)  (unknown)
```

**Comment by borisfom** [comment]
It may be related to this:

cudnn test in torch currently fails on systems with non-identical multiple GPUs.
Here, fix pending : https://github.com/torch/cutorch/issues/239

**Comment by alfredox10** [comment]
Hmm well both of my GPUs are identical, same brand, model, everything. I am running PNY GTX 780 Tis

**Comment by lukeyeager** [comment]
@borisfom - note that this is a Caffe issue, not Torch.

**Comment by thatguymike** [comment]
@alfredox10 Can you send one of us your prototxt and batch size?  We thought in cudnnv3 we had fixed all out of bounds writes, but if we can replicate locally we can find it hopefully with enough time to fix this in the final release of cuDNNv4

**Comment by alfredox10** [comment]
Sure I'll attach it here. Batch size is 64, but it also happens with 128. Note the full training does complete about 1 of about every 4 attempts. My dataset size is 181,157 train, 20,128 test images.

solver: http://pastebin.com/zJG1Y1LE
train_test model: http://pastebin.com/ZQy3PBdE

**Comment by lukeyeager** [comment]
@alfredox10 sorry for the late response. Can you check to see if your issue is resolved when using v0.14?

**Comment by alfredox10** [comment]
Hey Luke yes the issue has been resolved in 0.14
